site_name: My Docs
theme:
  name: material

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys

plugins:
  - drawio
  - search
  - mermaid2
  - panzoom
  - git-revision-date
